USE BIClass

DROP SCHEMA IF EXISTS [PKSequence]
GO
CREATE SCHEMA [PKSequence]
GO
CREATE SEQUENCE [PKSequence].[DataSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[DimCustomerSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[DimGenderSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[DimMaritalStatusSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[DimOccupationSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[DimOrderDateSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[DimProductSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE 
GO
CREATE SEQUENCE [PKSequence].[DimProductCategorySequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[DimProductSubcategorySequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[DimTerritorySequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[SalesManagersSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[WorkflowStepsSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO
CREATE SEQUENCE [PKSequence].[UserAuthorizationSequenceObject]
    AS int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    NO CYCLE
    CACHE
GO